language: node_js
sudo: false
cache: yarn
node_js:
  - 8
before_install:
  - export PATH=$HOME/.yarn/bin:$PATH
before_script:
  - yarn global add codecov
script:
  - yarn test
  - yarn lint
  - codecov
  - yarn run build:lib